gitGraph
  commit id:"Live Set"
  branch t1
  checkout t1
  commit id:"1-MIDI"
  commit id:"devices: 3"
  commit id:"Producer_Pal"
  commit id:"Adlib Delay | chains:…"
  commit id:"Basic Stereo Chorus J…"
  checkout main
  branch t2
  checkout t2
  commit id:"2-Audio"
  commit id:"devices: 0"
  checkout main
  branch t3
  checkout t3
  commit id:"3-Audio"
  commit id:"devices: 0"
  checkout main
  branch t4
  checkout t4
  commit id:"4-MIDI"
  commit id:"devices: 0"
  checkout main
  branch t5
  checkout t5
  commit id:"5-MIDI"
  commit id:"devices: 0"
  checkout main
  branch t6
  checkout t6
  commit id:"6-MIDI"
  commit id:"devices: 0"
  checkout main
  branch t7
  checkout t7
  commit id:"7-Cage Kit"
  commit id:"devices: 1"
  commit id:"Cage Kit | chains: 1"
  checkout main
  branch t8
  checkout t8
  commit id:"8-Audio"
  commit id:"devices: 0"
  checkout main
  branch t9
  checkout t9
  commit id:"9-Audio"
  commit id:"devices: 1"
  commit id:"Basic Stereo Chorus J…"
  checkout main
  branch r1
  checkout r1
  commit id:"A-Reverb | Cabinet Mic …"
  commit id:"devices: 2"
  commit id:"Reverb"
  commit id:"Cabinet Mic Mixer | c…"
  checkout main
  branch r2
  checkout r2
  commit id:"B-Delay"
  commit id:"devices: 1"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"devices: 0"

