gitGraph
  commit id:"Live Set"
  branch "1-MIDI"
  checkout "1-MIDI"
  commit id:"1-MIDI"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Producer Pal"
  checkout main
  branch "2-DS HH"
  checkout "2-DS HH"
  commit id:"2-DS HH"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"DS HH"
  checkout main
  branch "A-Reverb"
  checkout "A-Reverb"
  commit id:"A-Reverb"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Reverb"
  checkout main
  branch "B-Delay"
  checkout "B-Delay"
  commit id:"B-Delay"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"dev:0"

