kanban
  1-MIDI
    [MIDI 1-MIDI · MIDI · dev:1 · sends:2]
    [DEV Producer_Pal · Device]
  2-DS HH
    [MIDI 2-DS HH · MIDI · dev:1 · sends:2]
    [DEV DS HH · Device]
  A-Reverb
    [RET A-Reverb · Return · dev:1 · sends:2]
    [DEV Reverb · Device]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:0 · sends:0]

