gitGraph
  commit id:"Live Set"
  branch "1-5ths Glass Motion P…" order:1
  checkout "1-5ths Glass Motion P…"
  commit id:"1-5ths Glass Motion P…"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"Producer Pal"
  commit id:"5ths Glass Motion…"
  checkout main
  branch "2-E-Piano Faceplant" order:2
  checkout "2-E-Piano Faceplant"
  commit id:"2-E-Piano Faceplant"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"E-Piano Faceplant"
  commit id:"chains:1"
  commit id:"Ample Space Delay"
  commit id:"chains:3"
  checkout main
  branch "3-DS Clap" order:3
  checkout "3-DS Clap"
  commit id:"3-DS Clap"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"DS Clap"
  checkout main
  branch "4-5ths Detuned Pad" order:4
  checkout "4-5ths Detuned Pad"
  commit id:"4-5ths Detuned Pad"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"5ths Detuned Pad"
  commit id:"Alien Ice Cream"
  commit id:"chains:1"
  commit id:"Call Back"
  commit id:"chains:2"
  checkout main
  branch "A-Reverb" order:5
  checkout "A-Reverb"
  commit id:"A-Reverb"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Reverb"
  checkout main
  branch "B-Delay" order:6
  checkout "B-Delay"
  commit id:"B-Delay"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"dev:0"

