gitGraph
  commit id:"Live Set"
  branch "1-DS HH" order:1
  checkout "1-DS HH"
  commit id:"1-DS HH"
  commit id:"dev:4"
  commit id:"sends:2"
  commit id:"Note Echo"
  commit id:"STING!64"
  commit id:"DS HH"
  commit id:"LFO"
  checkout main
  branch "A-Reverb" order:2
  checkout "A-Reverb"
  commit id:"A-Reverb"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Reverb"
  checkout main
  branch "B-Delay" order:3
  checkout "B-Delay"
  commit id:"B-Delay"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"dev:0"

