kanban
  1-606 Core Kit
    [MIDI 1-606 Core Kit · MIDI · dev:2 · sends:2 · racks:1]
    [DEV Producer_Pal · Device]
    [RACK 606 Core Kit · Rack · chains:16 · pads:16]
  2-808 Core Kit
    [MIDI 2-808 Core Kit · MIDI · dev:1 · sends:2 · racks:1]
    [RACK 808 Core Kit · Rack · chains:16 · pads:16]
  3-808 Drifter
    [MIDI 3-808 Drifter · MIDI · dev:1 · sends:2 · racks:1]
    [RACK 808 Drifter · Rack · chains:1]
  4-A Soft Chord
    [MIDI 4-A Soft Chord · MIDI · dev:1 · sends:2]
    [DEV A Soft Chord · Device]
  5-Audio
    [AUD 5-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Basic Heavy Guitar Amp · Rack · chains:1]
  6-Audio
    [AUD 6-Audio · Audio · dev:1 · sends:2]
    [DEV Live Mode · Device]
  7-Audio
    [AUD 7-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Bit-ter · Rack · chains:2]
  8-Audio
    [AUD 8-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Car Listening Environ… · Rack · chains:1]
  9-Audio
    [AUD 9-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Electric Piano Amp · Rack · chains:1]
  10-DS Clap
    [MIDI 10-DS Clap · MIDI · dev:1 · sends:2]
    [DEV DS Clap · Device]
  11-MIDI
    [MIDI 11-MIDI · MIDI · dev:1 · sends:2]
    [DEV MIDI Monitor · Device]
  12-MIDI
    [MIDI 12-MIDI · MIDI · dev:1 · sends:2]
    [DEV Max MIDI Effect · Device]
  13-MIDI
    [MIDI 13-MIDI · MIDI · dev:1 · sends:2]
    [DEV STING!64 · Device]
  14-MIDI
    [MIDI 14-MIDI · MIDI · dev:1 · sends:2]
    [DEV MPE Control · Device]
  A-Reverb
    [RET A-Reverb | EQ Three Rack · Return · dev:2 · sends:2 · racks:1]
    [DEV Reverb · Device]
    [RACK EQ Three Rack · Rack · chains:1]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:3 · sends:0 · racks:3]
    [RACK Filter Phaser · Rack · chains:2]
    [RACK Master Bright & Edgy · Rack · chains:1]
    [RACK Master Bright & Edgy · Rack · chains:1]

