kanban
  1-MIDI
    [1-MIDI — MIDI — devices: 3 — sends: 2 — racks: 2]
    [Producer_Pal]
    [Adlib Delay — chains: 1]
    [Basic Stereo Chorus Jazz Amp — chains: 1]
  2-Audio
    [2-Audio — Audio — devices: 0 — sends: 2]
  3-Audio
    [3-Audio — Audio — devices: 0 — sends: 2]
  4-MIDI
    [4-MIDI — MIDI — devices: 0 — sends: 2]
  5-MIDI
    [5-MIDI — MIDI — devices: 0 — sends: 2]
  6-MIDI
    [6-MIDI — MIDI — devices: 0 — sends: 2]
  7-Cage Kit
    [7-Cage Kit — MIDI — devices: 1 — sends: 2 — racks: 1]
    [Cage Kit — chains: 1]
  8-Audio
    [8-Audio — Audio — devices: 0 — sends: 2]
  9-Audio
    [9-Audio — Audio — devices: 1 — sends: 2 — racks: 1]
    [Basic Stereo Chorus Jazz Amp — chains: 1]
  A-Reverb | Cabinet Mic Mixer
    [A-Reverb | Cabinet Mic Mixer — Return — devices: 2 — sends: 2 — racks: 1]
    [Reverb]
    [Cabinet Mic Mixer — chains: 1]
  B-Delay
    [B-Delay — Return — devices: 1 — sends: 2]
    [Delay]
  Main
    [Main — Master — devices: 0 — sends: 0]

