kanban
  1-MIDI
    [MIDI 1-MIDI · MIDI · dev:3 · sends:2 · racks:2]
    [DEV Producer_Pal · Device]
    [RACK Adlib Delay · Rack · chains:1]
    [RACK Basic Stereo Chorus J… · Rack · chains:1]
  2-Audio
    [AUD 2-Audio · Audio · dev:0 · sends:2]
  3-Audio
    [AUD 3-Audio · Audio · dev:0 · sends:2]
  4-MIDI
    [MIDI 4-MIDI · MIDI · dev:0 · sends:2]
  5-MIDI
    [MIDI 5-MIDI · MIDI · dev:0 · sends:2]
  6-MIDI
    [MIDI 6-MIDI · MIDI · dev:0 · sends:2]
  7-Cage Kit
    [MIDI 7-Cage Kit · MIDI · dev:1 · sends:2 · racks:1]
    [RACK Cage Kit · Rack · chains:1]
  8-Audio
    [AUD 8-Audio · Audio · dev:0 · sends:2]
  9-Audio
    [AUD 9-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Basic Stereo Chorus J… · Rack · chains:1]
  A-Reverb
    [RET A-Reverb | Cabinet Mic … · Return · dev:2 · sends:2 · racks:1]
    [DEV Reverb · Device]
    [RACK Cabinet Mic Mixer · Rack · chains:1]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:0 · sends:0]

