gitGraph
  commit id:"Live Set"
  branch "Coffee Leaf"
  checkout "Coffee Leaf"
  commit id:"Coffee Leaf"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Coffee Leaf"
  commit id:"Utility"
  commit id:"Happy Bees"
  commit id:"chains:1"
  checkout main
  branch "Strum"
  checkout "Strum"
  commit id:"Strum"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Strum-o-Matic"
  commit id:"chains:1"
  commit id:"Auto Filter Legacy"
  commit id:"Audio Effect Rack"
  commit id:"chains:1"
  checkout main
  branch "Drums"
  checkout "Drums"
  commit id:"Drums"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Drum Rack"
  commit id:"chains:11"
  commit id:"pads:11"
  commit id:"Utility"
  checkout main
  branch "The Beat Of History"
  checkout "The Beat Of History"
  commit id:"The Beat Of History"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"The Beat Of Histo…"
  commit id:"chains:1"
  checkout main
  branch "Mello"
  checkout "Mello"
  commit id:"Mello"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Mello"
  commit id:"Angry Bees"
  commit id:"chains:1"
  checkout main
  branch "Rose Bass"
  checkout "Rose Bass"
  commit id:"Rose Bass"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Rose Bass"
  commit id:"chains:1"
  commit id:"Reese Talk"
  commit id:"chains:1"
  commit id:"Utility"
  checkout main
  branch "Sub Sub Bass"
  checkout "Sub Sub Bass"
  commit id:"Sub Sub Bass"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Sub Sub Bass"
  commit id:"chains:1"
  checkout main
  branch "Guit Layter"
  checkout "Guit Layter"
  commit id:"Guit Layter"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Guit Layter"
  commit id:"chains:1"
  commit id:"Robot Glitter"
  commit id:"chains:1"
  commit id:"Compressor"
  checkout main
  branch "Transform Seed"
  checkout "Transform Seed"
  commit id:"Transform Seed"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Metallic High Sho…"
  checkout main
  branch "Vacuum"
  checkout "Vacuum"
  commit id:"Vacuum"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Vacuum Flute"
  commit id:"chains:1"
  commit id:"Audio Effect Rack"
  commit id:"chains:1"
  checkout main
  branch "Vocal Main"
  checkout "Vocal Main"
  commit id:"Vocal Main"
  commit id:"dev:4"
  commit id:"sends:2"
  commit id:"racks:3"
  commit id:"S Suppresor"
  commit id:"chains:1"
  commit id:"Articulator"
  commit id:"chains:2"
  commit id:"Reverb"
  commit id:"Fadeaway"
  commit id:"chains:1"
  checkout main
  branch "Vocal Harmony"
  checkout "Vocal Harmony"
  commit id:"Vocal Harmony"
  commit id:"dev:4"
  commit id:"sends:2"
  commit id:"racks:3"
  commit id:"S Suppresor"
  commit id:"chains:1"
  commit id:"Articulator"
  commit id:"chains:2"
  commit id:"Reverb"
  commit id:"Fadeaway"
  commit id:"chains:1"
  checkout main
  branch "Vocal Hum"
  checkout "Vocal Hum"
  commit id:"Vocal Hum"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Reverb"
  checkout main
  branch "Vocal Adlib"
  checkout "Vocal Adlib"
  commit id:"Vocal Adlib"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Adlib Delay"
  commit id:"chains:1"
  checkout main
  branch "Rainstorm"
  checkout "Rainstorm"
  commit id:"Rainstorm"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Rainstorm"
  commit id:"chains:1"
  checkout main
  branch "A-Reverb"
  checkout "A-Reverb"
  commit id:"A-Reverb"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Verb Expand"
  commit id:"chains:1"
  checkout main
  branch "B-Delay"
  checkout "B-Delay"
  commit id:"B-Delay"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"dev:1"

