kanban
  Tracks
    [1-MIDI — MIDI — devices: 3 — sends: 2 — racks: 2]
    [2-Audio — Audio — devices: 0 — sends: 2]
    [3-Audio — Audio — devices: 0 — sends: 2]
    [4-MIDI — MIDI — devices: 0 — sends: 2]
    [5-MIDI — MIDI — devices: 0 — sends: 2]
    [6-MIDI — MIDI — devices: 0 — sends: 2]
    [7-Cage Kit — MIDI — devices: 1 — sends: 2 — racks: 1]
    [8-Audio — Audio — devices: 0 — sends: 2]
    [9-Audio — Audio — devices: 1 — sends: 2 — racks: 1]
  Return Tracks
    [A-Reverb | Cabinet Mic Mixer — Return — devices: 2 — sends: 2 — racks: 1]
    [B-Delay — Return — devices: 1 — sends: 2]
  Master
    [Main — Master — devices: 0 — sends: 0]

