gitGraph
  commit id:"Live Set"
  branch T1
  checkout T1
  commit id:"1-MIDI"
  commit id:"devices: 3"
  commit id:"Producer_Pal"
  commit id:"Adlib Delay | chains:…"
  commit id:"Basic Stereo Chorus J…"
  checkout main
  branch T2
  checkout T2
  commit id:"2-Audio"
  commit id:"devices: 0"
  checkout main
  branch T3
  checkout T3
  commit id:"3-Audio"
  commit id:"devices: 0"
  checkout main
  branch T4
  checkout T4
  commit id:"4-MIDI"
  commit id:"devices: 0"
  checkout main
  branch T5
  checkout T5
  commit id:"5-MIDI"
  commit id:"devices: 0"
  checkout main
  branch T6
  checkout T6
  commit id:"6-MIDI"
  commit id:"devices: 0"
  checkout main
  branch T7
  checkout T7
  commit id:"7-Cage Kit"
  commit id:"devices: 1"
  commit id:"Cage Kit | chains: 1"
  checkout main
  branch T8
  checkout T8
  commit id:"8-Audio"
  commit id:"devices: 0"
  checkout main
  branch T9
  checkout T9
  commit id:"9-Audio"
  commit id:"devices: 1"
  commit id:"Basic Stereo Chorus J…"
  checkout main
  branch R1
  checkout R1
  commit id:"A-Reverb | Cabinet Mic …"
  commit id:"devices: 2"
  commit id:"Reverb"
  commit id:"Cabinet Mic Mixer | c…"
  checkout main
  branch R2
  checkout R2
  commit id:"B-Delay"
  commit id:"devices: 1"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"devices: 0"

