kanban
  1-5ths Glass Moti…
    [MIDI 1-5ths Glass Motion Pad · MIDI · dev:2 · sends:2]
    [DEV Producer_Pal · Device]
    [DEV 5ths Glass Motion Pad · Device]
  2-E-Piano Facepla…
    [MIDI 2-E-Piano Faceplant · MIDI · dev:2 · sends:2 · racks:2]
    [RACK E-Piano Faceplant · Rack · chains:1]
    [RACK Ample Space Delay · Rack · chains:3]
  3-DS Clap
    [MIDI 3-DS Clap · MIDI · dev:1 · sends:2]
    [DEV DS Clap · Device]
  4-5ths Detuned Pad
    [MIDI 4-5ths Detuned Pad · MIDI · dev:3 · sends:2 · racks:2]
    [DEV 5ths Detuned Pad · Device]
    [RACK Alien Ice Cream · Rack · chains:1]
    [RACK Call Back · Rack · chains:2]
  A-Reverb
    [RET A-Reverb | Basic Lead G… · Return · dev:2 · sends:2 · racks:1]
    [DEV Reverb · Device]
    [RACK Basic Lead Guitar Amp · Rack · chains:1]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:2 · sends:0 · racks:2]
    [RACK Alien Ice Cream · Rack · chains:1]
    [RACK Ample Space Delay · Rack · chains:3]

