kanban
  1-DS HH
    [MIDI 1-DS HH · MIDI · dev:4 · sends:2]
    [DEV Note Echo · Device]
    [DEV STING!64 · Device]
    [DEV DS HH · Device]
    [DEV LFO · Device]
  2-Audio
    [AUD 2-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Jittery Swells · Rack · chains:1]
  3-Audio
    [AUD 3-Audio · Audio · dev:1 · sends:2 · racks:1]
    [RACK Harmonic Tremolo · Rack · chains:1]
  4-BNYX Boot Kit
    [MIDI 4-BNYX Boot Kit · MIDI · dev:1 · sends:2 · racks:1]
    [RACK BNYX Boot Kit · Rack · chains:1]
  5-Balafon Bright
    [MIDI 5-Balafon Bright · MIDI · dev:1 · sends:2]
    [DEV Balafon Bright · Device]
  A-Reverb
    [RET A-Reverb · Return · dev:1 · sends:2]
    [DEV Reverb · Device]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:2 · sends:0 · racks:2]
    [RACK Major Wah · Rack · chains:2]
    [RACK Master Bright & Edgy · Rack · chains:1]

