kanban
  1-DS HH
    [MIDI 1-DS HH · MIDI · dev:4 · sends:2]
    [DEV Note Echo · Device]
    [DEV STING!64 · Device]
    [DEV DS HH · Device]
    [DEV LFO · Device]
  A-Reverb
    [RET A-Reverb · Return · dev:1 · sends:2]
    [DEV Reverb · Device]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:0 · sends:0]

