gitGraph
  commit id:"Ableton Live Set | 120 BPM | tracks: 9"
  branch track_0_1_1_midi_midi
  checkout track_0_1_1_midi_midi
  commit id:"1-MIDI | MIDI | devices: 3 | sends: 2"
  commit id:"Producer_Pal | Device"
  commit id:"Adlib Delay | RackDevice | chains: 1"
  commit id:"Basic Stereo Chorus Jazz Amp | RackDevice | chains: 1"
  checkout main
  branch track_1_2_2_audio_audio
  checkout track_1_2_2_audio_audio
  commit id:"2-Audio | Audio | devices: 0 | sends: 2"
  checkout main
  branch track_2_3_3_audio_audio
  checkout track_2_3_3_audio_audio
  commit id:"3-Audio | Audio | devices: 0 | sends: 2"
  checkout main
  branch track_3_4_4_midi_midi
  checkout track_3_4_4_midi_midi
  commit id:"4-MIDI | MIDI | devices: 0 | sends: 2"
  checkout main
  branch track_4_5_5_midi_midi
  checkout track_4_5_5_midi_midi
  commit id:"5-MIDI | MIDI | devices: 0 | sends: 2"
  checkout main
  branch track_5_6_6_midi_midi
  checkout track_5_6_6_midi_midi
  commit id:"6-MIDI | MIDI | devices: 0 | sends: 2"
  checkout main
  branch track_6_7_7_cage_kit_midi
  checkout track_6_7_7_cage_kit_midi
  commit id:"7-Cage Kit | MIDI | devices: 1 | sends: 2"
  commit id:"Cage Kit | RackDevice | chains: 1"
  checkout main
  branch track_7_8_8_audio_audio
  checkout track_7_8_8_audio_audio
  commit id:"8-Audio | Audio | devices: 0 | sends: 2"
  checkout main
  branch track_8_9_9_audio_audio
  checkout track_8_9_9_audio_audio
  commit id:"9-Audio | Audio | devices: 1 | sends: 2"
  commit id:"Basic Stereo Chorus Jazz Amp | RackDevice | chains: 1"
  checkout main
  branch return_0_1_a_reverb_cabinet_mic_mixer_return
  checkout return_0_1_a_reverb_cabinet_mic_mixer_return
  commit id:"A-Reverb | Cabinet Mic Mixer | Return | devices: 2 | sends: 2"
  commit id:"Reverb | Device"
  commit id:"Cabinet Mic Mixer | RackDevice | chains: 1"
  checkout main
  branch return_1_2_b_delay_return
  checkout return_1_2_b_delay_return
  commit id:"B-Delay | Return | devices: 1 | sends: 2"
  commit id:"Delay | Device"
  checkout main
  commit id:"Main | Master | devices: 0"

