gitGraph
  commit id:"Live Set"
  branch "T1 — Coffee Leaf"
  checkout "T1 — Coffee Leaf"
  commit id:"Coffee Leaf"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Coffee Leaf"
  commit id:"Utility"
  commit id:"Happy Bees"
  commit id:"chains:1"
  checkout main
  branch "T2 — Strum"
  checkout "T2 — Strum"
  commit id:"Strum"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Strum-o-Matic"
  commit id:"chains:1"
  commit id:"Auto Filter Legacy"
  commit id:"Audio Effect Rack"
  commit id:"chains:1"
  checkout main
  branch "T3 — Drums"
  checkout "T3 — Drums"
  commit id:"Drums"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Drum Rack"
  commit id:"chains:11"
  commit id:"pads:11"
  commit id:"Utility"
  checkout main
  branch "T4 — The Beat Of History"
  checkout "T4 — The Beat Of History"
  commit id:"The Beat Of History"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"The Beat Of Histo…"
  commit id:"chains:1"
  checkout main
  branch "T5 — Mello"
  checkout "T5 — Mello"
  commit id:"Mello"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Mello"
  commit id:"Angry Bees"
  commit id:"chains:1"
  checkout main
  branch "T6 — Rose Bass"
  checkout "T6 — Rose Bass"
  commit id:"Rose Bass"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Rose Bass"
  commit id:"chains:1"
  commit id:"Reese Talk"
  commit id:"chains:1"
  commit id:"Utility"
  checkout main
  branch "T7 — Sub Sub Bass"
  checkout "T7 — Sub Sub Bass"
  commit id:"Sub Sub Bass"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Sub Sub Bass"
  commit id:"chains:1"
  checkout main
  branch "T8 — Guit Layter"
  checkout "T8 — Guit Layter"
  commit id:"Guit Layter"
  commit id:"dev:3"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Guit Layter"
  commit id:"chains:1"
  commit id:"Robot Glitter"
  commit id:"chains:1"
  commit id:"Compressor"
  checkout main
  branch "T9 — Transform Seed"
  checkout "T9 — Transform Seed"
  commit id:"Transform Seed"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Metallic High Sho…"
  checkout main
  branch "T10 — Vacuum"
  checkout "T10 — Vacuum"
  commit id:"Vacuum"
  commit id:"dev:2"
  commit id:"sends:2"
  commit id:"racks:2"
  commit id:"Vacuum Flute"
  commit id:"chains:1"
  commit id:"Audio Effect Rack"
  commit id:"chains:1"
  checkout main
  branch "T11 — Vocal Main"
  checkout "T11 — Vocal Main"
  commit id:"Vocal Main"
  commit id:"dev:4"
  commit id:"sends:2"
  commit id:"racks:3"
  commit id:"S Suppresor"
  commit id:"chains:1"
  commit id:"Articulator"
  commit id:"chains:2"
  commit id:"Reverb"
  commit id:"Fadeaway"
  commit id:"chains:1"
  checkout main
  branch "T12 — Vocal Harmony"
  checkout "T12 — Vocal Harmony"
  commit id:"Vocal Harmony"
  commit id:"dev:4"
  commit id:"sends:2"
  commit id:"racks:3"
  commit id:"S Suppresor"
  commit id:"chains:1"
  commit id:"Articulator"
  commit id:"chains:2"
  commit id:"Reverb"
  commit id:"Fadeaway"
  commit id:"chains:1"
  checkout main
  branch "T13 — Vocal Hum"
  checkout "T13 — Vocal Hum"
  commit id:"Vocal Hum"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Reverb"
  checkout main
  branch "T14 — Vocal Adlib"
  checkout "T14 — Vocal Adlib"
  commit id:"Vocal Adlib"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Adlib Delay"
  commit id:"chains:1"
  checkout main
  branch "T15 — Rainstorm"
  checkout "T15 — Rainstorm"
  commit id:"Rainstorm"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Rainstorm"
  commit id:"chains:1"
  checkout main
  branch "R1 — A-Reverb"
  checkout "R1 — A-Reverb"
  commit id:"A-Reverb"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"racks:1"
  commit id:"Verb Expand"
  commit id:"chains:1"
  checkout main
  branch "R2 — B-Delay"
  checkout "R2 — B-Delay"
  commit id:"B-Delay"
  commit id:"dev:1"
  commit id:"sends:2"
  commit id:"Delay"
  checkout main
  commit id:"Main"
  commit id:"dev:1"

