kanban
  Coffee Leaf
    [MIDI Coffee Leaf · MIDI · dev:3 · sends:2 · racks:1]
    [DEV Coffee Leaf · Device]
    [DEV Utility · Device]
    [RACK Happy Bees · Rack · chains:1]
  Strum
    [MIDI Strum · MIDI · dev:3 · sends:2 · racks:2]
    [RACK Strum-o-Matic · Rack · chains:1]
    [DEV Auto Filter Legacy · Device]
    [RACK Audio Effect Rack · Rack · chains:1]
  Drums
    [MIDI Drums · MIDI · dev:2 · sends:2 · racks:1]
    [RACK Drum Rack · Rack · chains:11 · pads:11]
    [DEV Utility · Device]
  The Beat Of Histo…
    [MIDI The Beat Of History · MIDI · dev:1 · sends:2 · racks:1]
    [RACK The Beat Of History · Rack · chains:1]
  Mello
    [MIDI Mello · MIDI · dev:2 · sends:2 · racks:1]
    [DEV Mello · Device]
    [RACK Angry Bees · Rack · chains:1]
  Rose Bass
    [MIDI Rose Bass · MIDI · dev:3 · sends:2 · racks:2]
    [RACK Rose Bass · Rack · chains:1]
    [RACK Reese Talk · Rack · chains:1]
    [DEV Utility · Device]
  Sub Sub Bass
    [MIDI Sub Sub Bass · MIDI · dev:1 · sends:2 · racks:1]
    [RACK Sub Sub Bass · Rack · chains:1]
  Guit Layter
    [MIDI Guit Layter · MIDI · dev:3 · sends:2 · racks:2]
    [RACK Guit Layter · Rack · chains:1]
    [RACK Robot Glitter · Rack · chains:1]
    [DEV Compressor · Device]
  Transform Seed
    [MIDI Transform Seed · MIDI · dev:1 · sends:2]
    [DEV Metallic High Short · Device]
  Vacuum
    [MIDI Vacuum · MIDI · dev:2 · sends:2 · racks:2]
    [RACK Vacuum Flute · Rack · chains:1]
    [RACK Audio Effect Rack · Rack · chains:1]
  Vocal Main
    [AUD Vocal Main · Audio · dev:4 · sends:2 · racks:3]
    [RACK S Suppresor · Rack · chains:1]
    [RACK Articulator · Rack · chains:2]
    [DEV Reverb · Device]
    [RACK Fadeaway · Rack · chains:1]
  Vocal Harmony
    [AUD Vocal Harmony · Audio · dev:4 · sends:2 · racks:3]
    [RACK S Suppresor · Rack · chains:1]
    [RACK Articulator · Rack · chains:2]
    [DEV Reverb · Device]
    [RACK Fadeaway · Rack · chains:1]
  Vocal Hum
    [AUD Vocal Hum · Audio · dev:1 · sends:2]
    [DEV Reverb · Device]
  Vocal Adlib
    [AUD Vocal Adlib · Audio · dev:1 · sends:2 · racks:1]
    [RACK Adlib Delay · Rack · chains:1]
  Rainstorm
    [MIDI Rainstorm · MIDI · dev:1 · sends:2 · racks:1]
    [RACK Rainstorm · Rack · chains:1]
  A-Reverb
    [RET A-Reverb · Return · dev:1 · sends:2 · racks:1]
    [RACK Verb Expand · Rack · chains:1]
  B-Delay
    [RET B-Delay · Return · dev:1 · sends:2]
    [DEV Delay · Device]
  Main
    [MAIN Main · Master · dev:1 · sends:0 · racks:1]
    [RACK Patience Master · Rack · chains:1]

